---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iam.miloapis.com
  resources:
  - users
  verbs:
  - get
- apiGroups:
  - notification.miloapis.com
  resources:
  - emails
  - emailtemplates
  verbs:
  - get
- apiGroups:
  - notification.miloapis.com
  resources:
  - emails/status
  verbs:
  - get
  - update
