apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: email-provider-resend
spec:
  parentRefs:
    - name: external-gateway
      namespace: envoy-gateway-system
      sectionName: resend
  hostnames:
    - resend.staging.env.datum.net
    - resend.prod.env.datum.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: resend-webhook
          kind: Service
          port: 8090
